name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build package
      run: swift build -v -Xswiftc -suppress-warnings
    - name: Run package tests
      run: swift test -v -Xswiftc -suppress-warnings

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Install pod and test (iOS)
      run: >-
        cd Xcode-Testing

        pod install

        xcodebuild
        -workspace JobQueue.xcworkspace
        -scheme JobQueue
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3'
        test
