name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Swift Package
      run: swift build -v -Xswiftc -suppress-warnings
    - name: Run Swift Package Tests
      run: swift test -v -Xswiftc -suppress-warnings

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Install Dependencies for Test Targets
      working-directory: ./Xcode-Testing
      run: pod install

    - name: Force Xcode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app

    - name: Run iOS Tests
      working-directory: ./Xcode-Testing
      run: >-
        xcodebuild
        -workspace JobQueue.xcworkspace
        -scheme Tests.iOS
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3'
        test
