name: Swift

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build package
      run: swift build -v -Xswiftc -suppress-warnings
    - name: Run package tests
      run: swift test -v -Xswiftc -suppress-warnings

    - name: Install Cocoapods
    - run: gem install cocoapods

    - name: Move to Xcode-Testing directory
    - run: cd Xcode-Testing

    - name: Install dependencies
    - run: pod install

    - name: Test (iOS/Pod)
    - run: >-
        xcodebuild
        -workspace JobQueue.xcworkspace
        -scheme JobQueue
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3'
        test
